<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageTags>$(XtiAppName);$(XtiAppType);$(XtiVersion);</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XTI_WebApp.Api\XTI_WebApp.Api.csproj" />
	</ItemGroup>

</Project>
