<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageTags>$(XtiAppName);$(XtiAppType);$(XtiVersion);</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7" />
		<PackageReference Include="XTI_Core.Extensions" Version="1.10.26-dev260424141958857" />
		<PackageReference Include="XTI_Secrets.Extensions" Version="1.8.14-dev260424143319067" />
		<PackageReference Include="XTI_TempLog.Extensions" Version="1.2.38-dev260424145059777" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XTI_App.Api\XTI_App.Api.csproj" />
		<ProjectReference Include="..\XTI_App.Secrets\XTI_App.Secrets.csproj" />
	</ItemGroup>

</Project>
